version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0418
      POSTGRES_DB: 66days
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
